#示例配置信息

#其他配置文件,可以使用绝对路径
#或者相对于 anylink 二进制文件的路径

#数据文件
db_type = "sqlite3"
db_source = "./conf/anylink.db"
#远程API
hrpc_addr = "https://air5g.com/api"
hrpc_secret = "02ec2f8ba"
#证书文件
cert_file = "./conf/vpn_cert.crt"
cert_key = "./conf/vpn_cert.key"
files_path = "./conf/files"
log_level = "debug"

#系统名称
issuer = "SensAir"
#后台管理用户
admin_user = "admin"
#pass 123456
admin_pass = "$2a$10$UQ7C.EoPifDeJh6d8.31TeSPQU7hM/NOM2nixmBucJpAuXDQNqNke"
jwt_secret = "hijklm.9874563210.tyuiop"

#服务监听地址
server_addr = ":443"
#后台服务监听地址
admin_addr = ":8800"


#客户端分配的ip地址
ipv4_master = "eth0"
ipv4_cidr = "10.16.0.0/16"
ipv4_gateway = "10.16.0.1"
ipv4_start = "10.16.0.2"
ipv4_end = "10.16.200.200"

#是否自动添加nat
iptables_nat = true


#客户端显示详细错误信息(线上环境慎开启)
display_error = false


